### PR TITLE
[WIP] Add destination folder for XML files

### PR DESCRIPTION
**Pull request by roya0045**
Greetings,

First of all I wanted to thank you for this great plugin.

I am opening this PR to add a way to save the xml files instead of losing them in the temporary folder.

To do so I have to change some parts of your API and rework the UI 
image

The changes are not fully tested at the moment as I am short on time. I'll try to test and validate my changes. I still made the PR in case you wanted some more time to review it or propose some other things.

Thanks!

### CODE REVIEW

**Comment by sandroklippel** [comment]
Thanks for your contribution.

**Comment by roya0045** [comment]
@sandroklippel Glad to help, I'll try to test it this week ( as its a work in progress) and if anything I might have to make another PR. Thanks for the good work on the plugin!

**Comment by sandroklippel** [comment]
I made few fixes and added the project folder as a the default folder for the output directory dialog. I'm working on other minor improvements and fixes and I think I'll be releasing it as a new version soon. 

Feel free to make any other changes.

**Comment by roya0045** [comment]
Excellent! TBH the only major element missing was having a folder to simply store the xml since whenever I closed the project I couldn't get the images back. And my colleagues couldn't see them either.

**Pull request merged**
